version: "3"
services:
  db:
    image: "postgres:latest"
    container_name: "sdc_postgres"
    environment:
      DATABASE_URL: postgres://christianferdinand@db:5432/qanda
      POSTGRES_USER: christianferdinand
      POSTGRES_DB: qanda
      POSTGRES_HOST: "postgresql"
    ports:
      - "5432:5432"
    volumes:
      - sdc_questions:/var/lib/postgresql/data
      - ./lib/pgdump:/docker-entrypoint-initdb.d
  web:
    build: .
    ports:
      - "8000:3000"
    depends_on:
      - "db"
    links:
      - "db"
    environment:
      NODE_ENV: docker
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  sdc_questions:
