version: 2.1
jobs:
  build:
    working_directory: ~/questions-and-answers
    docker:
      - image: circleci/node:10.16.0
      - image: circleci/postgres:latest

    steps:
      - checkout
      - restore_cache:
          keys:
            dependency-cache-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found

      - run:
          name: Install npm packages
          command: npm install

      - save_cache:
          paths:
            - ./node_modules
          key: dependency-cache-{{ checksum "package-lock.json" }}
      # checking if the bulding builds correctly
      - run:
          environment:
            POSTGRES_USER: christianferdinand
            POSTGRES_DATABASE: qanda
            POSTGRES_HOST: 3.134.181.210
            POSTGRES_PORT: 5432
          name: Jest Test
          command: npm run test -- -u
