version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.0
      - image: circleci/postgres:latest

    steps:
      - checkout
      - restore_cache:
          keys:
            dependency-cache-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found

      - run:
          name: Install npm packages
          command: npm install

      - save_cache:
          paths:
            - ./node_modules
          key: dependency-cache-{{ checksum "package-lock.json" }}
      # checking if the bulding builds correctly
      - run:
          name: webpack Build test
          command: npm run build-test

      # run tests!
      - run:
          name: Jest Test
          context: Questions
          command: npm run test -- -u
