version: 2.1
jobs:
  build:
    working_directory: ~/questions-and-answers
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - restore_cache:
          keys:
            dependency-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
      - run:
          name: Install npm packages
          command: npm install

      - save_cache:
          paths:
            - ./node_modules
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Jest Test
          environment:
            PGUSER: christianferdinand
            PGDATABASE: qanda
            PGHOST: 3.134.181.210 #TODO: Change to use a postgres image and build the db using a sample file
            PGPORT: 5432
          command: npm run test -- -u
