version: 2
 jobs:
   build:
     docker:
       - image: circleci/node:10.16.0
     steps:
       - checkout

       - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

       - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # checking if the bulding builds correctly
      - run:
          name: webpack Build Dev
          command: npm run build-dev

      # run tests!
      - run:
          name: Jest Test
          command: npm test -- -u