version: 2
 jobs:
   build:
     docker:
       - image: circleci/node:10.16.0
     steps:
      - checkout
       
       working_directory: ~/repo

      - restore_cache:
          keys:
            dependency-cache-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found

      - run: npm install

      - save_cache:
          paths:
            - ./node_modules
          key: dependency-cache-{{ checksum "package-lock.json" }}
      # checking if the bulding builds correctly
      - run:
          name: webpack Build Dev
          command: npm run build-dev

      # run tests!
      - run:
          name: Jest Test
          command: npm run test -- -u